POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@user.com",
  "password": "admin",
  "role": "ADMIN"
}

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiaWF0IjoxNzQ3MjY2NDQ2LCJleHAiOjE3NDcyNzM2NDZ9.ba30XsxjL7lTYaAmKFJkychkZqUPjjYbt3swLFVvHUQ

### 
GET http://localhost:3000/users/cmaogm43a0000fv3om4rdxddx

###
PATCH http://localhost:3000/users/cmaogm43a0000fv3om4rdxddx
Content-Type: application/json

{
  "name": "JUNIN",
  "email": "JUNIN@user.com",
  "password": "GRAUZ",
  "role": "READER"
}


###
DELETE http://localhost:3000/users/cmaogm43a0000fv3om4rdxddx

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@user.com",
  "password": "admin"
}